[phases]
[phases.install]
  server = "cd server && npm install"
  client = "cd client && npm install"

[phases.build]
  server = "cd server && npm run build"
  client = "cd client && npm run build"

[phases.start]
  server = "cd server && npm start"

[start]
  cmd = "cd server && npm start"
